[versions]
androidGradlePlugin = "8.1.1"
ksp = "1.9.10-1.0.13"
agp = "8.4.0"
compose = "1.0.0-beta01"
hamcrest = "2.2"
hiltAndroidTesting = "2.51.1"
hiltNavigationCompose = "1.2.0"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.5.0"
appcompat = "1.7.0"
kotlinTest = "2.0.20"
material = "1.12.0"
activity = "1.9.0"

coroutines = "1.8.1"
mockitoCore = "4.0.0"
navigationCompose = "2.8.3"
okhttp = "4.12.0"
pagingCompose = "3.3.2"
retrofit = "2.11.0"
rules = "1.6.1"
runner = "1.5.0"
serialization-converter = "1.0.0"
kotlinx-serialization = "1.7.1"
turbine = "1.0.0"
uiTestManifest = "1.7.5"
viewModel = "2.4.0"
runtime = "2.8.3"
datastore = "1.0.0"
datastore-preferences = "1.0.0"
protobuf-javalite = "3.18.0"
paging = "3.3.1"
room = "2.6.1"
navigationTesting = "2.8.3"
compose-bom = "2024.09.02"

kapt = "1.5.30"
plugin-serialization = "2.0.0"
protobuf = "0.9.1"

hilt = "2.51.1"
junitKtx = "1.2.1"
uiTestJunit4Android = "1.7.4"
jetbrainsKotlinJvm = "2.0.0"

[libraries]
# dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

# compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
compose-glide = { module = "com.github.bumptech.glide:compose", version.ref = "compose" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewModel" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-android", version.ref = "runtime" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigationTesting" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }

androidx-paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }

androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinTest" }
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "uiTestJunit4Android" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoCore" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoCore" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoCore" }

# room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

# hilt
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt"}
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidTesting" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }

# network
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "serialization-converter" }

# serialization
jetbrains-kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# datastore & protobuf
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
protobuf = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf-javalite" }

# coroutines
jetbrains-kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
jetbrains-kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin-serialization" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }


[bundles]
coroutines = ["jetbrains-kotlinx-coroutines", "jetbrains-kotlinx-coroutines-test"]
compose = ["androidx-foundation", "androidx-foundation", "androidx-runtime", "androidx-ui", "androidx-material3", "androidx-runtime-livedata", "androidx-hilt-navigation-compose", "androidx-navigation-compose"]
compose-debug = ["androidx-ui-tooling"]